export const YorubaMapper: Record<string, string> = {
"ONE": "Kinni",
"TWO": "Keji",
"THREE": "Keta",
"FOUR": "Kerin",
"FIVE": "Karun-un",
"SIX": "Kefa",
"SEVEN": "Keje",
"EIGHT": "Kejo",
"NINE": "Kesan-an",
"TEN": "Kewaa",
"ELEVEN": "Kokanla",
"TWELVE": "Kejila",
"THIRTEEN": "Ketala",
"FOURTEEN": "Kerinla",
"FIFTEEN": "Karundinlogun",
"SIXTEEN": "Kerindinlogun",
"SEVENTEEN": "Ketadinlogun",
"EIGHTEEN": "Kejidinlogan",
"NINETEEN": "Kokandinlogun",
"TWENTY": "Ogun",
"TWENTY_ONE": "Kokanlelogun",
"TWENTY_TWO": "Kejilelogun",
"TWENTY_THREE": "Ketalelogun",
"TWENTY_FOUR": "Kerinlelogun",
"TWENTY_FIVE": "Karundinlogbon",
"TWENTY_SIX": "Kerindinlogbon"
}
